GO_BUILD_LINUX   = GOOS=linux GOARCH=amd64 go build
GO_BUILD_WINDOWS = GOOS=windows GOARCH=amd64 go build

.all: clean ballotbox

ballotbox:
	@echo "=== Compiling BallotBox for every OS ==="
	@mkdir -p build/ballotbox
	$(GO_BUILD_LINUX) -o build/ballotbox cmd/ballotbox.go
	$(GO_BUILD_WINDOWS) -o build/ballotbox cmd/ballotbox.go

clean: 
	rm -rf bin/