name: campus_vote
description: "Campus Vote - A digital election registry."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  easy_sidemenu: ^0.6.0
  ffigen: ^11.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  # GoLang FFI
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
