// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CampusVoteClient is the client API for CampusVote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampusVoteClient interface {
	CreateVoter(ctx context.Context, in *Voter, opts ...grpc.CallOption) (*StatusCode, error)
	GetVoterByStudentId(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*Voter, error)
	SetVoterAsVoted(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*StatusCode, error)
	CheckVoterStatus(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*StatusCode, error)
	GetElectionStats(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ElectionStats, error)
}

type campusVoteClient struct {
	cc grpc.ClientConnInterface
}

func NewCampusVoteClient(cc grpc.ClientConnInterface) CampusVoteClient {
	return &campusVoteClient{cc}
}

func (c *campusVoteClient) CreateVoter(ctx context.Context, in *Voter, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := c.cc.Invoke(ctx, "/CampusVote/CreateVoter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campusVoteClient) GetVoterByStudentId(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*Voter, error) {
	out := new(Voter)
	err := c.cc.Invoke(ctx, "/CampusVote/GetVoterByStudentId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campusVoteClient) SetVoterAsVoted(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := c.cc.Invoke(ctx, "/CampusVote/SetVoterAsVoted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campusVoteClient) CheckVoterStatus(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := c.cc.Invoke(ctx, "/CampusVote/CheckVoterStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campusVoteClient) GetElectionStats(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ElectionStats, error) {
	out := new(ElectionStats)
	err := c.cc.Invoke(ctx, "/CampusVote/GetElectionStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampusVoteServer is the server API for CampusVote service.
// All implementations must embed UnimplementedCampusVoteServer
// for forward compatibility
type CampusVoteServer interface {
	CreateVoter(context.Context, *Voter) (*StatusCode, error)
	GetVoterByStudentId(context.Context, *StudentId) (*Voter, error)
	SetVoterAsVoted(context.Context, *StudentId) (*StatusCode, error)
	CheckVoterStatus(context.Context, *StudentId) (*StatusCode, error)
	GetElectionStats(context.Context, *Void) (*ElectionStats, error)
	mustEmbedUnimplementedCampusVoteServer()
}

// UnimplementedCampusVoteServer must be embedded to have forward compatible implementations.
type UnimplementedCampusVoteServer struct {
}

func (UnimplementedCampusVoteServer) CreateVoter(context.Context, *Voter) (*StatusCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVoter not implemented")
}
func (UnimplementedCampusVoteServer) GetVoterByStudentId(context.Context, *StudentId) (*Voter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoterByStudentId not implemented")
}
func (UnimplementedCampusVoteServer) SetVoterAsVoted(context.Context, *StudentId) (*StatusCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVoterAsVoted not implemented")
}
func (UnimplementedCampusVoteServer) CheckVoterStatus(context.Context, *StudentId) (*StatusCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckVoterStatus not implemented")
}
func (UnimplementedCampusVoteServer) GetElectionStats(context.Context, *Void) (*ElectionStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetElectionStats not implemented")
}
func (UnimplementedCampusVoteServer) mustEmbedUnimplementedCampusVoteServer() {}

// UnsafeCampusVoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampusVoteServer will
// result in compilation errors.
type UnsafeCampusVoteServer interface {
	mustEmbedUnimplementedCampusVoteServer()
}

func RegisterCampusVoteServer(s grpc.ServiceRegistrar, srv CampusVoteServer) {
	s.RegisterService(&CampusVote_ServiceDesc, srv)
}

func _CampusVote_CreateVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Voter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampusVoteServer).CreateVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote/CreateVoter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampusVoteServer).CreateVoter(ctx, req.(*Voter))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampusVote_GetVoterByStudentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampusVoteServer).GetVoterByStudentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote/GetVoterByStudentId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampusVoteServer).GetVoterByStudentId(ctx, req.(*StudentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampusVote_SetVoterAsVoted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampusVoteServer).SetVoterAsVoted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote/SetVoterAsVoted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampusVoteServer).SetVoterAsVoted(ctx, req.(*StudentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampusVote_CheckVoterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampusVoteServer).CheckVoterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote/CheckVoterStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampusVoteServer).CheckVoterStatus(ctx, req.(*StudentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampusVote_GetElectionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampusVoteServer).GetElectionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote/GetElectionStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampusVoteServer).GetElectionStats(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// CampusVote_ServiceDesc is the grpc.ServiceDesc for CampusVote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CampusVote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CampusVote",
	HandlerType: (*CampusVoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVoter",
			Handler:    _CampusVote_CreateVoter_Handler,
		},
		{
			MethodName: "GetVoterByStudentId",
			Handler:    _CampusVote_GetVoterByStudentId_Handler,
		},
		{
			MethodName: "SetVoterAsVoted",
			Handler:    _CampusVote_SetVoterAsVoted_Handler,
		},
		{
			MethodName: "CheckVoterStatus",
			Handler:    _CampusVote_CheckVoterStatus_Handler,
		},
		{
			MethodName: "GetElectionStats",
			Handler:    _CampusVote_GetElectionStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
