// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: vote.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VoteClient is the client API for Vote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoteClient interface {
	CreateVoter(ctx context.Context, in *Voter, opts ...grpc.CallOption) (*StatusCode, error)
	GetVoterByStudentId(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*Voter, error)
	RegisterVote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*StatusCode, error)
	CheckVoterStatus(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*StatusCode, error)
	GetElectionStats(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ElectionStats, error)
}

type voteClient struct {
	cc grpc.ClientConnInterface
}

func NewVoteClient(cc grpc.ClientConnInterface) VoteClient {
	return &voteClient{cc}
}

func (c *voteClient) CreateVoter(ctx context.Context, in *Voter, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := c.cc.Invoke(ctx, "/CampusVote.Vote/CreateVoter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteClient) GetVoterByStudentId(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*Voter, error) {
	out := new(Voter)
	err := c.cc.Invoke(ctx, "/CampusVote.Vote/GetVoterByStudentId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteClient) RegisterVote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := c.cc.Invoke(ctx, "/CampusVote.Vote/RegisterVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteClient) CheckVoterStatus(ctx context.Context, in *StudentId, opts ...grpc.CallOption) (*StatusCode, error) {
	out := new(StatusCode)
	err := c.cc.Invoke(ctx, "/CampusVote.Vote/CheckVoterStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteClient) GetElectionStats(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ElectionStats, error) {
	out := new(ElectionStats)
	err := c.cc.Invoke(ctx, "/CampusVote.Vote/GetElectionStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoteServer is the server API for Vote service.
// All implementations must embed UnimplementedVoteServer
// for forward compatibility
type VoteServer interface {
	CreateVoter(context.Context, *Voter) (*StatusCode, error)
	GetVoterByStudentId(context.Context, *StudentId) (*Voter, error)
	RegisterVote(context.Context, *VoteReq) (*StatusCode, error)
	CheckVoterStatus(context.Context, *StudentId) (*StatusCode, error)
	GetElectionStats(context.Context, *Void) (*ElectionStats, error)
	mustEmbedUnimplementedVoteServer()
}

// UnimplementedVoteServer must be embedded to have forward compatible implementations.
type UnimplementedVoteServer struct {
}

func (UnimplementedVoteServer) CreateVoter(context.Context, *Voter) (*StatusCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVoter not implemented")
}
func (UnimplementedVoteServer) GetVoterByStudentId(context.Context, *StudentId) (*Voter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoterByStudentId not implemented")
}
func (UnimplementedVoteServer) RegisterVote(context.Context, *VoteReq) (*StatusCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVote not implemented")
}
func (UnimplementedVoteServer) CheckVoterStatus(context.Context, *StudentId) (*StatusCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckVoterStatus not implemented")
}
func (UnimplementedVoteServer) GetElectionStats(context.Context, *Void) (*ElectionStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetElectionStats not implemented")
}
func (UnimplementedVoteServer) mustEmbedUnimplementedVoteServer() {}

// UnsafeVoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoteServer will
// result in compilation errors.
type UnsafeVoteServer interface {
	mustEmbedUnimplementedVoteServer()
}

func RegisterVoteServer(s grpc.ServiceRegistrar, srv VoteServer) {
	s.RegisterService(&Vote_ServiceDesc, srv)
}

func _Vote_CreateVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Voter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServer).CreateVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote.Vote/CreateVoter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServer).CreateVoter(ctx, req.(*Voter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vote_GetVoterByStudentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServer).GetVoterByStudentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote.Vote/GetVoterByStudentId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServer).GetVoterByStudentId(ctx, req.(*StudentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vote_RegisterVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServer).RegisterVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote.Vote/RegisterVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServer).RegisterVote(ctx, req.(*VoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vote_CheckVoterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServer).CheckVoterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote.Vote/CheckVoterStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServer).CheckVoterStatus(ctx, req.(*StudentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vote_GetElectionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServer).GetElectionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CampusVote.Vote/GetElectionStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServer).GetElectionStats(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// Vote_ServiceDesc is the grpc.ServiceDesc for Vote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CampusVote.Vote",
	HandlerType: (*VoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVoter",
			Handler:    _Vote_CreateVoter_Handler,
		},
		{
			MethodName: "GetVoterByStudentId",
			Handler:    _Vote_GetVoterByStudentId_Handler,
		},
		{
			MethodName: "RegisterVote",
			Handler:    _Vote_RegisterVote_Handler,
		},
		{
			MethodName: "CheckVoterStatus",
			Handler:    _Vote_CheckVoterStatus_Handler,
		},
		{
			MethodName: "GetElectionStats",
			Handler:    _Vote_GetElectionStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vote.proto",
}
