name: campus_vote
description: "Campus Vote - A digital election registry."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  archive: ^3.6.1
  encrypt: ^5.0.3
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.0
  form_builder_validators: ^10.0.1
  get_it: ^7.7.0
  grpc: ^3.2.4
  intl: any
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pointycastle: ^3.9.1
  protobuf: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sidebarx: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dependency_validator: ^4.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
